name: Update M3U

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    env: 
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Generate playlist
        run: python generate_playlist.py

      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/updated_playlist.m3u
          git commit -m "Auto udpate playlist" || echo "No changes"
          git push
